// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3O-u748YOAXextWLp6mV4LmEKQzizEWw',
    appId: '1:522236673438:android:c02002b72e4285a1dcea8f',
    messagingSenderId: '522236673438',
    projectId: 'homeease-3e717',
    storageBucket: 'homeease-3e717.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGFU23l-fQmiYyYQ0Fy4wCyDsydobvcfw',
    appId: '1:522236673438:ios:cba6c5038b81e99fdcea8f',
    messagingSenderId: '522236673438',
    projectId: 'homeease-3e717',
    storageBucket: 'homeease-3e717.firebasestorage.app',
    androidClientId: '522236673438-jmoookuna3hd7l7qkt84ks060ceijvlm.apps.googleusercontent.com',
    iosClientId: '522236673438-nadoq2bml3nkqhr6r5raoasviu90cv6p.apps.googleusercontent.com',
    iosBundleId: 'com.example.homeease',
  );
}
